export const RESEARCHER_LIST_REQUEST = 'RESEARCHER_LIST_REQUEST'
export const RESEARCHER_LIST_SUCCESS = 'RESEARCHER_LIST_SUCCESS'
export const RESEARCHER_LIST_FAIL = 'RESEARCHER_LIST_FAIL'

export const RESEARCHER_APPROVE_REQUEST = 'RESEARCHER_APPROVE_REQUEST'
export const RESEARCHER_APPROVE_SUCCESS = 'RESEARCHER_APPROVE_SUCCESS'
export const RESEARCHER_APPROVE_FAIL = 'RESEARCHER_APPROVE_FAIL'

export const RESEARCHER_DELETE_REQUEST = 'RESEARCHER_DELETE_REQUEST'
export const RESEARCHER_DELETE_SUCCESS = 'RESEARCHER_DELETE_SUCCESS'
export const RESEARCHER_DELETE_FAIL = 'RESEARCHER_DELETE_FAIL'

export const LOADING_RESEARCHER = 'LOADING_RESEARCHER'
export const FETCH_RESEARCHER = 'FETCH_RESEARCHER'
export const APPROVE_RESEARCHER = 'APPROVE_RESEARCHER'
export const EDIT_RESEARCHER = 'EDIT_RESEARCHER'
export const DELETE_RESEARCHER = 'DELETE_RESEARCHER'
export const ERROR_RESEARCHER = 'ERROR_RESEARCHER'
